services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Replace with your actual start command
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: supersecretkey  # Update with your actual key
