version: 1
services:
  - type: web
    name: app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential libglib2.0-dev pkg-config && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
