services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Replace with your start command
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: supersecretkey
      - key: PYTHON_VERSION
        value: 3.11  # Set the desired Python version here
